name: Check for broken links

on:
  - push
  - pull_request

jobs:
  check:
    if: github.repository == 'orderlynetwork/documentation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Mintlify CLI
        run: |
          npm i -g mintlify

      - name: Check links
        run: |
          mintlify broken-links
