name: Publish Source

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Push to public repository
        run: |
          git remote add publish git@github.com:OrderlyNetwork/documentation-public.git
          git push publish main
